"""
Purpose: ORM Model representing the core business events of the platform.
Responsibilities:
- Define the `Event` entity for storing state transitions generated by the Event Engine.
- Provide a robust, index-optimized structure for high-volume timeseries analytics.
Dependencies: sqlalchemy, src.models.base
"""

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Enum, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base, UUIDMixin


class EventType(str, enum.Enum):
    """
    Strict taxonomy of all possible domain events generated by the platform.
    Using an Enum prevents silent analytical bugs caused by string typos in the Event Engine.
    """
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    REENTRY = "REENTRY"
    ZONE_ENTER = "ZONE_ENTER"
    ZONE_EXIT = "ZONE_EXIT"
    ZONE_DWELL = "ZONE_DWELL"
    BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
    BILLING_QUEUE_ABANDON = "BILLING_QUEUE_ABANDON"


class Event(Base, UUIDMixin):
    """
    Represents an immutable, append-only domain event triggered by a Visitor's physical movement.
    
    WARNING: This table will grow massively (millions of rows per day for 40 stores). 
    While SQLAlchemy handles the mapping, at the database level this table MUST be 
    partitioned by time (e.g., daily partitions via pg_partman) to prevent index bloat 
    and maintain query performance.
    """
    __tablename__ = "events"

    # Crucial for filtering events by store efficiently (the most common query pattern)
    store_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("stores.id", ondelete="CASCADE"), nullable=False, index=True
    )
    
    visitor_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("visitors.id", ondelete="CASCADE"), nullable=False, index=True
    )
    
    # Optional: Not all events are tied to a specific internal polygon (e.g., store ENTRY/EXIT)
    zone_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("zones.id", ondelete="CASCADE"), nullable=True, index=True
    )

    # native_enum=False forces SQLAlchemy to use VARCHAR instead of PostgreSQL ENUM types.
    # This makes adding new event types in the future much easier without complex DB migrations.
    event_type: Mapped[EventType] = mapped_column(
        Enum(EventType, native_enum=False), nullable=False, index=True
    )

    # We do NOT use TimestampMixin here. An event occurs at an exact moment in time 
    # and is immutable (no `updated_at` needed). This represents the actual physical event time, 
    # which might differ from database insertion time if edge nodes buffer while offline.
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)

    # Schema-less payload for event-specific data.
    # Example for ZONE_DWELL: {"dwell_duration_seconds": 142}
    # Example for BILLING_QUEUE_JOIN: {"queue_depth_estimate": 4}
    metadata_payload: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSONB, nullable=True)

    def __repr__(self) -> str:
        return f"<Event(id={self.id}, type={self.event_type}, time={self.timestamp.isoformat()})>"
